In [3]:
import numpy as np

In [12]:
my_list=[[1,2,3,4],[5,6,7,8]]

In [13]:
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
a=np.array(my_list)

In [15]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.arange(0,12,2)    #step size

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.ones(2)    #1D

array([1., 1.])

In [20]:
np.ones((3,4))    #2D

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.eye(5)       #unit matrice

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.linspace(0,100,50)     #spacing between digits

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [24]:
np.random.rand(5)

array([0.7391586 , 0.15232007, 0.27604366, 0.22475925, 0.15449612])

In [25]:
np.random.rand(5,5)

array([[0.34780908, 0.53731666, 0.24841908, 0.92880385, 0.98048081],
       [0.30398873, 0.93194977, 0.58966856, 0.83141561, 0.30437779],
       [0.68479468, 0.1169923 , 0.15859021, 0.04104913, 0.86684394],
       [0.77930693, 0.84912379, 0.49940137, 0.78688131, 0.68097726],
       [0.64901472, 0.893164  , 0.36538237, 0.04959636, 0.42979285]])

In [26]:
a>5

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [27]:
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [33]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
a[a>5]            #conditional selection

array([6, 7, 8])

In [37]:
b=np.arange(50).reshape(5,10)

In [38]:
b                       #row & column starting from index 0

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
np.zeros(2)

array([0., 0.])

In [40]:
b[2:4,4:6]          #slicing

array([[24, 25],
       [34, 35]])